### ISSUE TITLE
Can't start RabbitMQ in my application.

### ISSUE THREAD

**Issue by kenshinji** [AlejandroRivera/embedded-rabbitmq#37]
I have a `App` class.

```
public class App {
    public static void main(String[] args) {
        EmbeddedRabbitMqConfig config = new EmbeddedRabbitMqConfig.Builder().build();
        EmbeddedRabbitMq rabbitMq = new EmbeddedRabbitMq(config);
        rabbitMq.start();
    }
}
```

However when I was trying to start it, the following error poped up.

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" io.arivera.oss.embedded.rabbitmq.extract.ExtractionException: Download file 'C:\Users\wangzen\.embeddedrabbitmq\rabbitmq-server-windows-3.6.9.zip' was not found or is not accessible.
	at io.arivera.oss.embedded.rabbitmq.extract.BasicExtractor$ZipExtractor.run(BasicExtractor.java:223)
	at io.arivera.oss.embedded.rabbitmq.extract.BasicExtractor.run(BasicExtractor.java:39)
	at io.arivera.oss.embedded.rabbitmq.extract.CachedExtractor.run(CachedExtractor.java:22)
	at io.arivera.oss.embedded.rabbitmq.EmbeddedRabbitMq.extract(EmbeddedRabbitMq.java:75)
	at io.arivera.oss.embedded.rabbitmq.EmbeddedRabbitMq.start(EmbeddedRabbitMq.java:60)
	at App.main(App.java:22)
Caused by: java.util.zip.ZipException: archive is not a ZIP archive
	at org.apache.commons.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(ZipFile.java:806)
	at org.apache.commons.compress.archivers.zip.ZipFile.positionAtCentralDirectory(ZipFile.java:736)
	at org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(ZipFile.java:481)
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:216)
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:192)
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:153)
	at io.arivera.oss.embedded.rabbitmq.extract.BasicExtractor$ZipExtractor.run(BasicExtractor.java:221)
	... 5 more
```
I started the application with Administrator's privilege.

**Comment by AlejandroRivera** [comment]
Did you verify if the file `C:\Users\wangzen\.embeddedrabbitmq\rabbitmq-server-windows-3.6.9.zip` actually existed and contained a valid zip file?

**Comment by AlejandroRivera** [comment]
If you want to see what the logs look like for a successful download/execution, see the build logs starting in line 241:
https://ci.appveyor.com/project/AlejandroRivera/embedded-rabbitmq/build/1.0.121-master#L241

**Comment by kenshinji** [comment]
I ran this application behind a company firewall, so I thought this issue might be caused by missing proxy configuration. After I tried 
```
        EmbeddedRabbitMqConfig.Builder configBuilder = new EmbeddedRabbitMqConfig.Builder();
        configBuilder.downloadProxy("<PROXY_HOST_ADDRESS>", <PORT>);
        EmbeddedRabbitMqConfig config = configBuilder.build();
```
it told me there is an error of `403`

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" io.arivera.oss.embedded.rabbitmq.download.DownloadException: Could not download 'http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.9/rabbitmq-server-windows-3.6.9.zip' to 'C:\Users\wangzen\.embeddedrabbitmq\rabbitmq-server-windows-3.6.9.zip'
	at io.arivera.oss.embedded.rabbitmq.download.BasicDownloader$DownloadTask.run(BasicDownloader.java:69)
	at io.arivera.oss.embedded.rabbitmq.download.BasicDownloader.run(BasicDownloader.java:33)
	at io.arivera.oss.embedded.rabbitmq.download.CachedDownloader.download(CachedDownloader.java:37)
	at io.arivera.oss.embedded.rabbitmq.download.CachedDownloader.run(CachedDownloader.java:26)
	at io.arivera.oss.embedded.rabbitmq.EmbeddedRabbitMq.download(EmbeddedRabbitMq.java:70)
	at io.arivera.oss.embedded.rabbitmq.EmbeddedRabbitMq.start(EmbeddedRabbitMq.java:59)
	at App.main(App.java:25)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.9/rabbitmq-server-windows-3.6.9.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at io.arivera.oss.embedded.rabbitmq.apache.commons.io.FileUtils.copyUrlToFile(FileUtils.java:106)
	at io.arivera.oss.embedded.rabbitmq.download.BasicDownloader$DownloadTask.run(BasicDownloader.java:60)
	... 6 more
```

**Comment by kenshinji** [comment]
@AlejandroRivera no, the file hasn't been downloaded.

**Comment by AlejandroRivera** [comment]
If you open the URL `http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.9/rabbitmq-server-windows-3.6.9.zip` in your browser, are you able to successfully download the file?
If so, I suppose you have a proxy configured in your browser, but does it require a username/password? The proxy functionality in this project does not currently support authenticated proxies. If you're up to it, feel free to submit a PR.

Another alternative is:

a) manually download the file somewhere (example: `c:\rabbitmq\downloads\rabbitmq-server-windows-3.6.9.zip`
b) use the following config (or similar)
```
EmbeddedRabbitMqConfig config = new EmbeddedRabbitMqConfig.Builder()
   .downloadTarget(new File("c:\\rabbitmq\\downloads"))
   .extractionFolder(new File("c:\\rabbitmq\\servers"))
   .useCachedDownload(true)
   .deleteDownloadedFileOnErrors(false)
   .build();
```
d) run your app again. It should use the already manually downloaded file

**Comment by kenshinji** [comment]
Yes, I can download RabbitMQ through the URL by my browser, and the proxy doesn't need authentication.
Somehow it works. I don't know whether it is due to restarting my Windows box. However there is still a problem. I have an RabbitMQ server(v3.6.5) installed and running locally, the `App` won't be able to start up unless I stop my RabbitMQ(v3.6.5) server mannually, and once I ran the code I posted here previously. I can't run my old version RabbitMQ successfully. So I'm wondering do we need to check whether there is an RabbitMQ instance running before our `embedded-rabbitmq` start.

**Comment by AlejandroRivera** [comment]
Since you're not providing any sort of logs showing what error happened, my best guess is that you're running into port binding issues.

Try to define a random port. See http://static.javadoc.io/io.arivera.oss/embedded-rabbitmq/1.2.1/io/arivera/oss/embedded/rabbitmq/EmbeddedRabbitMqConfig.Builder.html#randomPort()

**Comment by kenshinji** [comment]
Here is the error log when I started `App` and there is another RabbitMQ installed running locally.

```
Exception in thread "main" io.arivera.oss.embedded.rabbitmq.helpers.StartupException: Could not confirm RabbitMQ Server initialization completed successfully within 3000ms
	at io.arivera.oss.embedded.rabbitmq.helpers.StartupHelper.waitForConfirmation(StartupHelper.java:74)
	at io.arivera.oss.embedded.rabbitmq.helpers.StartupHelper.call(StartupHelper.java:50)
	at io.arivera.oss.embedded.rabbitmq.EmbeddedRabbitMq.run(EmbeddedRabbitMq.java:79)
	at io.arivera.oss.embedded.rabbitmq.EmbeddedRabbitMq.start(EmbeddedRabbitMq.java:61)
	at App.main(App.java:27)

**Comment by AlejandroRivera** [comment]
That's the stacktrace from the Java application waiting for the server to start. 
There should be some other log (usually right above) that shows why the rabbitmq server was not able to startup. 

```
01:06:03.316 INFO    Thread-3 i.a.o.e.r.E.P.rabbitmq-server -               RabbitMQ 3.5.7. Copyright (C) 2007-2015 Pivotal Software, Inc.
01:06:03.316 INFO    Thread-3 i.a.o.e.r.E.P.rabbitmq-server -   ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
01:06:03.316 INFO    Thread-3 i.a.o.e.r.E.P.rabbitmq-server -   ##  ##
01:06:03.316 INFO    Thread-3 i.a.o.e.r.E.P.rabbitmq-server -   ##########  Logs: C:/Users/appveyor/AppData/Roaming/RabbitMQ/log/rabbit@APPVYR-WIN.log
01:06:03.316 INFO    Thread-3 i.a.o.e.r.E.P.rabbitmq-server -   ######  ##        C:/Users/appveyor/AppData/Roaming/RabbitMQ/log/rabbit@APPVYR-WIN-sasl.log
01:06:03.316 INFO    Thread-3 i.a.o.e.r.E.P.rabbitmq-server -   ##########
01:06:03.959 INFO    Thread-3 i.a.o.e.r.E.P.rabbitmq-server -               Starting broker...
```
The error is usually right below these logs. Perhaps something that looks like:
`{could_not_start,rabbitmq_stomp,{{shutdown,{failed_to_start_child,'rabbit_stomp_listener_sup_:::61613',{shutdown,
{failed_to_start_child,tcp_listener,{cannot_listen,{0,0,0,0,0,0,0,0},61613,eacces}}}}},{rabbit_stomp,start,[normal,[]]}}}`

**Comment by AlejandroRivera** [comment]
I'm closing this issue since there's been no activity for a while and everything points to be a local setup issue and not a bug in the code.
